DATALOADER:
  NUM_WORKERS: 8
INPUT:
  MIN_SIZE_TRAIN: (480, 480)
  MAX_SIZE_TRAIN: 800
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 800
  FORMAT: RGB
MODEL:
  WEIGHTS: "data/model_final.pth"
  DEVICE: cpu
  ROI_HEADS:
    NUM_CLASSES: 3
    SCORE_THRESH_TEST: 0.5
  RETINANET:
    SCORE_THRESH_TEST: 0.5
  PANOPTIC_FPN:
    COMBINE:
      INSTANCES_CONFIDENCE_THRESH: 0.5
SOLVER:
  BASE_LR: 0.0375
  MAX_ITER: 9000
  STEPS: (6000, 8000)
  IMS_PER_BATCH: 18
TEST:
  EVAL_PERIOD: 400
VERSION: 2
